### PR TITLE
Add vietnamese version link

### PR DESCRIPTION
**Pull request by nguyenvanduocit**

### CODE REVIEW

**Comment by camsong** [comment]
Can you squash these two commits into one? May refer to https://davidwalsh.name/squash-commits-git

**Comment by camsong** [comment]
image

A small issue, this link doesn't work, should be link to (##danh-mục)

**Comment by nguyenvanduocit** [comment]
I just fix anchor link.

**Comment by camsong** [comment]
Ok, the easy way is to save your changes first -> delete your fork and fork from here again -> apply your changes manually -> create a new PR.

**Comment by nguyenvanduocit** [comment]
Ok.

**Pull request closed without merging**
