### PR TITLE
Update on pt-br translation

### PR DESCRIPTION
**Pull request by joselitojunior**
- Fixed some semantic errors
- Added more portuguese expressions and terms
- Fixed some typos and ponctuation
- Entire table of contents in portuguese (when needed)
- Title of the page in portuguese

### CODE REVIEW

**Comment by camsong** [comment]
This anchor link is broken

image

**Comment by camsong** [comment]
image
broken too

**Comment by joselitojunior** [comment]
@camsong, something is wrong. Here on my repo (on the patch-1 branch) everything is working fine on my Chrome: https://github.com/joselitojunior/You-Dont-Need-jQuery/blob/patch-1/README.pt-BR.md

And, on my translation, there's no such thing as "CSS & Style". I'm using "CSS & Estilo", fully translated.
Are you seeing the appropriate file?

**Comment by camsong** [comment]
@joselitojunior  Yep, this PR is pretty good. My mistake to check the wrong file.
Great thanks for your contribution, please help to keep this up to date :+1:

**Comment by joselitojunior** [comment]
thx @camsong :rocket:

**Pull request merged**
