### PR TITLE
repair spelling and create for malay language

### PR DESCRIPTION
**Pull request by infacq**

### CODE REVIEW

**Comment by camsong** [comment]
Thanks for the contribution, really like it.
Can you also fix the merge conflicts and make a a squash after fixed that, so that we can get a cleaner commits history.
May refer to https://davidwalsh.name/squash-commits-git

**Comment by infacq** [comment]
ok i did as your suggestion

**Comment by camsong** [comment]
Thanks for your effect. Can you also combine all the commits in this PR. using `rebase` and do `squash` https://davidwalsh.name/squash-commits-git

**Comment by infacq** [comment]
i am not sure about rebase. I did follow the instructions from the link given but not sure what to expect

**Comment by camsong** [comment]
Let me do this, thanks for your contribution. please help to keep this update to date :+1:

**Comment by infacq** [comment]
sure no problem

**Pull request merged**
