### PR TITLE
jQuery empty()

### PR DESCRIPTION
**Pull request by annamalai-saro**

### CODE REVIEW

**Comment by kafeltz** [comment]
I'm wonder if this method for clearing could lead to memory leaks, for example, callback with Interval or Timeout attached in these destroyed elements.

**Comment by camsong** [comment]
@kafeltz it may cause memory leaks, but the reason is up to the developer. Before destroying elements, one should clean all interval or event listeners bind to that elements manually. It's easy to extract a method to do this automatically for a project, but it's hard or impossible to make that method suitable for all projects.

@annamalai-saro can you fix the conflicts?

**Comment by annamalai-saro** [comment]
@camsong  I agree with you ... Developer should take care of it .
I try to fix the conflicts and then ping u !

**Comment by kafeltz** [comment]
@camsong @annamalai-saro agreed, it's like to create a "destroy" function pattern in the class. But it's good to be aware of this problem.

**Pull request closed without merging**
