### PR TITLE
Update ko-KR

### PR DESCRIPTION
**Pull request by woneob**

### CODE REVIEW

**Comment by camsong** [comment]
thanks, can you squash those commits?

**Comment by item4** [comment]
Oh, good. I missed make PR. Nice translate. :)

**Comment by camsong** [comment]
@woneob If you don't know how to squash, the easy way is to save your changes first -> delete your fork and fork from here again -> apply your changes manually -> create a new PR.

**Comment by woneob** [comment]
I think I don't understand the meaning of Squash. I'll create a new PR soon.

**Pull request closed without merging**
